# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  [workflow_dispatch]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: abranch        
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: joesiltberg/gha_test
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        run: |
          docker build -t joesiltberg/gha_docker_test -f Dockerfile.windows .

      - name: Docker Push
        run: |
          docker push joesiltberg/gha_docker_test
